import type { Community, Conversation, Post } from "./types";

export const posts: Post[] = [
  {
    id: 1,
    communityId: "seed-campuslife",
    community: "c/campuslife",
    accent: "#6C3BFF",
    author: "chai.overthinker",
    time: "18m",
    flair: "Campus tea",
    title: "The library’s silent floor has its own main character now",
    body: "To whoever has been leaving tiny origami frogs on every desk: you have single-handedly fixed midterm week. Please never stop. 🐸",
    votes: 1284,
    comments: 86,
  },
  {
    id: 2,
    communityId: "seed-photography",
    community: "c/photography",
    accent: "#22D3EE",
    author: "grainy.days",
    time: "1h",
    flair: "Photo dump",
    title: "Campus after the rain looks like a coming-of-age film",
    image: "/campus-rain.svg",
    votes: 892,
    comments: 42,
  },
  {
    id: 3,
    communityId: "seed-foodies",
    community: "c/foodies",
    accent: "#FF5C8A",
    author: "noodlesat2am",
    time: "2h",
    flair: "Serious research",
    title: "Settle this: best food under ₹100 within walking distance?",
    body: "Budget is tight. Standards are not. Drop your sleeper picks below.",
    poll: [
      { label: "Anna’s dosa cart", percent: 48 },
      { label: "Gate 3 momos", percent: 31 },
      { label: "Canteen samosa + chai", percent: 21 },
    ],
    votes: 564,
    comments: 119,
  },
  {
    id: 4,
    communityId: "seed-campuslife",
    community: "c/campuslife",
    accent: "#6C3BFF",
    author: "lost.and.found",
    time: "3h",
    flair: "Help needed",
    title: "Found a silver ring near the north-block stairs",
    body: "It has a tiny star engraved inside. Tell me what else is engraved so I know it’s yours — I’ve left it with the student affairs desk.",
    votes: 346,
    comments: 28,
  },
  {
    id: 5,
    communityId: "seed-tech",
    community: "c/tech",
    accent: "#C7FF32",
    author: "shipit.sunday",
    time: "4h",
    flair: "Project showcase",
    title: "We built a live canteen queue tracker over the weekend",
    body: "It’s very scrappy, surprisingly accurate, and now open source. Looking for two people to help us test it during the lunch rush.",
    votes: 721,
    comments: 64,
  },
  {
    id: 6,
    communityId: "seed-music",
    community: "c/music",
    accent: "#FFB629",
    author: "minor.chords",
    time: "6h",
    flair: "Collab",
    title: "Need a bassist for the open mic set on Friday",
    body: "Three songs, one rehearsal, zero pressure. Indie-pop set with a slightly chaotic ending. DM if you’re interested.",
    votes: 188,
    comments: 31,
  },
];

export const events = [
  { id: "seed-indie-night", title: "Indie Night: Open Mic", description: "A campus night for discovering new voices, slightly nervous first-timers, and the people who cheer the loudest.", category: "Music", location: "The Amphitheatre", venueName: "VIT Chennai Amphitheatre", venueAddress: "VIT Chennai, Kelambakkam–Vandalur Road, Chennai", directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=12.8406,80.1534", campus: "Vellore Institute of Technology — Chennai", startsAt: "2026-09-02T18:30:00+05:30", capacity: 240, imageUrl: "/indie-night.svg" },
  { id: "seed-build-weird", title: "Build Something Weird", description: "A hands-on build day for ideas that are useful, delightful, or gloriously unnecessary.", category: "Tech", location: "Innovation Lab", venueName: "Innovation Lab", venueAddress: "VIT Chennai, Kelambakkam–Vandalur Road, Chennai", directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=12.8406,80.1534", campus: "Vellore Institute of Technology — Chennai", startsAt: "2026-09-05T10:00:00+05:30", capacity: 100, imageUrl: "/build-weird.svg" },
  { id: "seed-thrift-market", title: "Thrift & Zine Market", description: "Student-made zines, pre-loved clothes, tiny prints, and a very good afternoon outside.", category: "Culture", location: "North Quad", venueName: "North Quad", venueAddress: "VIT Chennai, Kelambakkam–Vandalur Road, Chennai", directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=12.8406,80.1534", campus: "Vellore Institute of Technology — Chennai", startsAt: "2026-09-08T16:00:00+05:30", capacity: 350, imageUrl: "/thrift-market.svg" },
  { id: "seed-run-club", title: "Sunset Run Club", description: "An easy social run around campus with all paces welcome and no one left behind.", category: "Sports", location: "Main Gate", venueName: "VIT Chennai Main Gate", venueAddress: "VIT Chennai, Kelambakkam–Vandalur Road, Chennai", directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=12.8406,80.1534", campus: "Vellore Institute of Technology — Chennai", startsAt: "2026-09-12T17:45:00+05:30", capacity: 60, imageUrl: "/run-club.svg" },
];

export const conversations: Conversation[] = [
  { id: 1, name: "Design Club Core", avatar: "DC", preview: "Mira: I’ve shared the final poster!", time: "2m", unread: 4, online: true, group: true },
  { id: 2, name: "Aarav", avatar: "AA", preview: "are we still on for chai?", time: "12m", unread: 1, online: true },
  { id: 3, name: "Hackathon team 🚀", avatar: "HT", preview: "Zoya: pushed the new build", time: "1h", group: true },
  { id: 4, name: "Naina", avatar: "NA", preview: "That photo is so good omg", time: "3h" },
  { id: 5, name: "Film Society", avatar: "FS", preview: "Kabir: voting closes tonight", time: "1d", group: true },
];

export const communities: Community[] = [
  { id: "seed-campuslife", creatorId: "system", name: "c/campuslife", members: "18.2k", color: "#6C3BFF", emoji: "⚡", iconUrl: "", bannerUrl: "", description: "Everything happening on campus, from wholesome to unhinged.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
  { id: "seed-photography", creatorId: "system", name: "c/photography", members: "6.8k", color: "#22D3EE", emoji: "📸", iconUrl: "", bannerUrl: "", description: "Frames, film rolls and finding the good light.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
  { id: "seed-foodies", creatorId: "system", name: "c/foodies", members: "12.4k", color: "#FF5C8A", emoji: "🍜", iconUrl: "", bannerUrl: "", description: "Real reviews, secret menus and eternal canteen debates.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
  { id: "seed-tech", creatorId: "system", name: "c/tech", members: "9.1k", color: "#C7FF32", emoji: "⌁", iconUrl: "", bannerUrl: "", description: "Builds, bugs, hackathons and the occasional existential crisis.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
  { id: "seed-music", creatorId: "system", name: "c/music", members: "7.5k", color: "#FFB629", emoji: "♫", iconUrl: "", bannerUrl: "", description: "Gigs, playlists, jam sessions and beautiful noise.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
  { id: "seed-thrift", creatorId: "system", name: "c/thrift", members: "3.2k", color: "#FF5C8A", emoji: "✿", iconUrl: "", bannerUrl: "", description: "Second-hand finds, styling help and sustainable swaps.", joined: false, privacy: "public", createdAt: 1_723_680_000_000, updatedAt: 1_723_680_000_000 },
];
