import type { CampusEvent, Community, Post } from "@/lib/types";

export const communities: Community[] = [
  {
    id: "c/campuslife",
    creatorId: "system",
    name: "Campus Life",
    members: "2.4k",
    color: "#4F46E5",
    emoji: "🎓",
    iconUrl: "",
    bannerUrl: "",
    description: "Campus updates, announcements, and student life stories from around the community.",
    joined: true,
    privacy: "public",
    role: "MEMBER",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: "c/tech-club",
    creatorId: "system",
    name: "Tech Club",
    members: "870",
    color: "#0EA5E9",
    emoji: "💻",
    iconUrl: "",
    bannerUrl: "",
    description: "Hackathons, project showcases, and tech networking for builders and innovators.",
    joined: false,
    privacy: "restricted",
    role: undefined,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
    updatedAt: Date.now() - 1000 * 60 * 60 * 6,
  },
  {
    id: "c/books-and-brews",
    creatorId: "system",
    name: "Books & Brews",
    members: "430",
    color: "#F59E0B",
    emoji: "📚",
    iconUrl: "",
    bannerUrl: "",
    description: "Reading circles, coffee chats, and thoughtful discussion around books and ideas.",
    joined: true,
    privacy: "public",
    role: "ADMIN",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
  },
];

export const events: CampusEvent[] = [
  {
    id: "evt-sunset-hacknight",
    creatorId: "system",
    title: "Sunset Hack Night",
    description: "Bring a laptop, team up, and build something fun with friends before the week starts.",
    category: "Workshop",
    location: "Innovation Hub",
    venueName: "Innovation Hub",
    venueAddress: "Main Campus, Building 12",
    directionsUrl: "https://maps.google.com/?q=Innovation+Hub",
    campus: "Main Campus",
    community: "c/tech-club",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    capacity: 80,
    imageUrl: "",
    customFormSchema: { version: 1, fields: [] },
    going: 44,
    waitlisted: 3,
    isCreator: false,
    isEventAdmin: false,
    canManageEvent: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 14,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
    month: "SEP",
    day: "03",
    time: "6:30 PM",
  },
  {
    id: "evt-cafe-book-club",
    creatorId: "system",
    title: "Café Book Club",
    description: "A relaxed evening of reading, coffee, and thoughtful conversation with classmates.",
    category: "Social",
    location: "Student Center Courtyard",
    venueName: "Student Center Courtyard",
    venueAddress: "Student Center Plaza",
    directionsUrl: "https://maps.google.com/?q=Student+Center+Courtyard",
    campus: "Main Campus",
    community: "c/books-and-brews",
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    capacity: 30,
    imageUrl: "",
    customFormSchema: { version: 1, fields: [] },
    going: 18,
    waitlisted: 0,
    isCreator: false,
    isEventAdmin: false,
    canManageEvent: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
    month: "SEP",
    day: "06",
    time: "7:00 PM",
  },
];

export const posts: Post[] = [
  {
    id: 1001,
    communityId: "c/campuslife",
    community: "Campus Life",
    accent: "#4F46E5",
    author: "Ari",
    time: "2h ago",
    title: "Welcome week volunteer signups are live",
    body: "We are looking for student volunteers to help with orientation booths, campus tours, and event setup. If you are free this Friday, sign up in the portal.",
    votes: 128,
    comments: 14,
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: 1002,
    communityId: "c/tech-club",
    community: "Tech Club",
    accent: "#0EA5E9",
    author: "Nia",
    time: "5h ago",
    title: "Project showcase call for student demos",
    body: "We are collecting demo submissions for the end-of-month showcase. Share a prototype, a research project, or a small app build you are proud of.",
    votes: 94,
    comments: 9,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
  },
];
